# Matrix Addition

## Definition

Matrix addition is defined only when two matrices have the same shape.

If:

A, B ∈ R^(m × n)

Then:

C = A + B

where:

C[i,j] = A[i,j] + B[i,j]

This is element-wise addition.

---

## Condition

shape(A) = shape(B)

If shapes differ → operation is undefined.

---

## Properties

1. Commutative  
   A + B = B + A

2. Associative  
   (A + B) + C = A + (B + C)

3. Identity element  
   A + 0 = A

4. Additive inverse  
   A + (−A) = 0


In [1]:
import numpy as np

# Example 1: Basic 2x2 matrix addition
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise addition
C = A + B

print("A + B:\n", C)


# Example 2: 3x3 matrices
X = np.array([[1, 0, 2],
              [-1, 3, 1],
              [3, 2, 0]])

Y = np.array([[0, 3, -1],
              [2, 1, 4],
              [1, 0, 5]])

Z = X + Y

print("\nX + Y:\n", Z)


# Example 3: Using explicit NumPy function
D = np.add(A, B)

print("\nUsing np.add():\n", D)


# Example 4: Shape mismatch error
M = np.array([[1, 2],
              [3, 4]])

N = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    result = M + N
except ValueError as e:
    print("\nError:", e)


A + B:
 [[ 6  8]
 [10 12]]

X + Y:
 [[1 3 1]
 [1 4 5]
 [4 2 5]]

Using np.add():
 [[ 6  8]
 [10 12]]

Error: operands could not be broadcast together with shapes (2,2) (2,3) 
