# Matrix Subtraction

## Definition

Matrix subtraction is defined only when two matrices have the same shape.

If:

A, B ∈ R^(m × n)

Then:

C = A − B

where:

C[i,j] = A[i,j] − B[i,j]

Subtraction is performed element-wise.

---

## Condition

shape(A) = shape(B)

If shapes differ → operation is undefined.

---

## Properties

1. Not commutative  
   A − B ≠ B − A

2. Can be written as addition  
   A − B = A + (−B)

3. Identity  
   A − 0 = A


In [1]:
import numpy as np

# Example 1: Basic 2x2 matrix subtraction
A = np.array([[5, 6],
              [7, 8]])

B = np.array([[1, 2],
              [3, 4]])

# Element-wise subtraction
C = A - B

print("A - B:\n", C)


# Example 2: 3x3 matrices
X = np.array([[4, 0, 2],
              [1, 3, 5],
              [6, 2, 1]])

Y = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])

Z = X - Y

print("\nX - Y:\n", Z)


# Example 3: Using explicit NumPy function
D = np.subtract(A, B)

print("\nUsing np.subtract():\n", D)


# Example 4: Showing non-commutativity
print("\nA - B:\n", A - B)
print("\nB - A:\n", B - A)


# Example 5: Shape mismatch error
M = np.array([[1, 2],
              [3, 4]])

N = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    result = M - N
except ValueError as e:
    print("\nError:", e)


A - B:
 [[4 4]
 [4 4]]

X - Y:
 [[ 3 -1  1]
 [-1  1  3]
 [ 3 -1 -2]]

Using np.subtract():
 [[4 4]
 [4 4]]

A - B:
 [[4 4]
 [4 4]]

B - A:
 [[-4 -4]
 [-4 -4]]

Error: operands could not be broadcast together with shapes (2,2) (2,3) 
