# Transpose of a Matrix

## Definition

The transpose of a matrix swaps rows and columns.

If:

A ∈ R^(m × n)

Then:

A^T ∈ R^(n × m)

where:

(A^T)[i,j] = A[j,i]

---

## Effect

Rows become columns.  
Columns become rows.

---

## Properties

1. (A^T)^T = A

2. (A + B)^T = A^T + B^T

3. (AB)^T = B^T A^T

4. (λA)^T = λA^T


In [1]:
import numpy as np

# Example 1: Basic transpose
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Using .T attribute
A_T = A.T

print("Matrix A:\n", A)
print("\nTranspose of A:\n", A_T)


# Example 2: Using np.transpose()
B = np.transpose(A)

print("\nUsing np.transpose():\n", B)


# Example 3: Transpose of square matrix
C = np.array([[1, 2],
              [3, 4]])

print("\nC:\n", C)
print("\nC^T:\n", C.T)


# Example 4: Verify (AB)^T = B^T A^T
X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

left = (X @ Y).T
right = Y.T @ X.T

print("\n( X @ Y )^T:\n", left)
print("\nY^T @ X^T:\n", right)


# Example 5: Transpose of a vector
v = np.array([[1, 2, 3]])  # row vector

print("\nRow vector:\n", v)
print("\nColumn vector (transpose):\n", v.T)


Matrix A:
 [[1 2 3]
 [4 5 6]]

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]

Using np.transpose():
 [[1 4]
 [2 5]
 [3 6]]

C:
 [[1 2]
 [3 4]]

C^T:
 [[1 3]
 [2 4]]

( X @ Y )^T:
 [[19 43]
 [22 50]]

Y^T @ X^T:
 [[19 43]
 [22 50]]

Row vector:
 [[1 2 3]]

Column vector (transpose):
 [[1]
 [2]
 [3]]
