# Matrix Power

## Definition

Matrix power is repeated matrix multiplication of a square matrix.

If:

A ∈ R^(n × n)

Then:

A^k = A · A · A ... (k times)

k must be an integer.

---

## Conditions

1. Matrix must be square.
2. k ≥ 0 (integer).

---

## Special Cases

A^0 = I  (Identity matrix)

A^1 = A

---

## Important

Matrix power uses matrix multiplication, NOT element-wise power.

A @ A  → matrix multiplication  
A ** 2 → element-wise power


In [1]:
import numpy as np

# Example 1: Basic square matrix
A = np.array([[1, 2],
              [3, 4]])

# Matrix squared (A^2)
A_squared = np.linalg.matrix_power(A, 2)

print("A^2:\n", A_squared)


# Example 2: Higher power
A_cubed = np.linalg.matrix_power(A, 3)

print("\nA^3:\n", A_cubed)


# Example 3: Power 0 gives identity matrix
A_zero = np.linalg.matrix_power(A, 0)

print("\nA^0 (Identity):\n", A_zero)


# Example 4: Compare matrix power vs element-wise power
elementwise = A ** 2   # squares each element individually

print("\nElement-wise A**2:\n", elementwise)
print("\nMatrix power A^2:\n", A_squared)


# Example 5: Non-square matrix error
B = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    result = np.linalg.matrix_power(B, 2)
except ValueError as e:
    print("\nError:", e)


A^2:
 [[ 7 10]
 [15 22]]

A^3:
 [[ 37  54]
 [ 81 118]]

A^0 (Identity):
 [[1 0]
 [0 1]]

Element-wise A**2:
 [[ 1  4]
 [ 9 16]]

Matrix power A^2:
 [[ 7 10]
 [15 22]]

Error: Last 2 dimensions of the array must be square
